SELECT * FROM new_pro_view ;

SELECT * FROM MEMBER;

SELECT NO,NAME,KIND,PRICE,SALEPRICE,MARGIN,CONTENT,IMAGE,DEL_USEYN,BEST_USEYN,REG_DATE FROM PRODUCT;

SELECT ID,PWD,NAME,EMAIL,ZIP_NO,ADDRESS,PHONE,UNSIGN_USEYN,JOIN_DATE FROM MEMBER WHERE ID = 'one';

 INSERT INTO MEMBER(ID, PWD, NAME, ZIP_NO, ADDRESS, PHONE) VALUES (?, ?,?, ?, ?, ?);
 
SELECT ZIP_NO,SIDO,GUGUN,DONG,ZIP_CODE,BUNJI FROM ADDRESS WHERE DONG LIKE '%'||'진달'||'%';

SELECT * FROM  CART;

SELECT * FROM CART

SELECT NO,MEMBERID,PNO,QUANTITY,RESULT_USEYN,REG_DATE FROM CART WHERE memberid = 'test' AND RESULT_USEYN='1' ORDER BY NO ASC;

insert into cart(MEMBERID, NO , quantity) values('one', 2, 1);
insert into cart(MEMBERID,PNO,QUANTITY,RESULT_USEYN,REG_DATE) values('test', 21, 3,'y', sysdate);

SELECT ONO, MID, MNAME, PHONE, zip_no, ADDRESS, DNO, ORDER_DATE, RESULT, PNO, PNAME, QUANTITY, SALEPRICE FROM ORDER_VIEW WHERE MID='test' AND RESULT LIKE 'y' AND ONO=21; 

DELETE ORDERS;
DELETE CART;
DELETE ORDER_DETAIL;

SELECT DNO,ONO,MID,ORDER_DATE,PNO,QUANTITY,MNAME,ZIP_NO,ADDRESS,PHONE,PNAME,SALEPRICE,RESULT FROM order_view WHERE MID='aaaaa' AND RESULT LIKE 'n' AND ONO=27;

SELECT * FROM ORDER_VIEW;



UPDATE ORDER_DETAIL
	SET RESULT_USEYN ='y'
	WHERE NO =60;

DNO,ONO,MID,ORDER_DATE,PNO,QUANTITY,MNAME,ZIP_NO,ADDRESS,PHONE,PNAME,SALEPRICE FROM ORDER_VIEW WHERE MID=:1  AND RESULT LIKE :2  AND ONO=:3  ,
DNO,ONO,MID,ORDER_DATE,PNO,QUANTITY,MNAME,ZIP_NO,ADDRESS,PHONE,PNAME,SALEPRICE,RESULT FROM ORDER_VIEW WHERE MID=? AND RESULT LIKE ? AND ONO=? 
DNO,ONO,MID,ORDER_DATE,PNO,QUANTITY,MNAME,ZIP_NO,ADDRESS,PHONE,PNAME,SALEPRICE,RESULT FROM ORDER_VIEW WHERE MID=? AND RESULT LIKE ? AND ONO=;

SELECT * FROM "MEMBER" m ;

SELECT MAX(no) FROM ORDERS;

SELECT * FROM ORDERS o ORDER BY no;
SELECT * FROM ORDER_DETAIL od ;


SELECT * FROM CART;

select od.NO,ONO,PNO,QUANTITY,RESULT_USEYN,ID,ORDER_DATE from ORDER_DETAIL od LEFT JOIN ORDERS o ON(o.NO = od.ONO ) where id='test' and result_useyn like '%'||'y'||'%' and o.NO=5;

select od.NO,ONO,PNO,QUANTITY,RESULT_USEYN,ID,ORDER_DATE from ORDER_DETAIL od LEFT JOIN ORDERS o ON(o.NO = od.ONO ) where id='test' and result_useyn='y' order by o.no DESC;



SELECT * FROM ORDERS;

select od.NO,ONO,PNO,QUANTITY,RESULT_USEYN,ID,ORDER_DATE from ORDER_DETAIL od LEFT JOIN ORDERS o ON(o.NO = od.ONO );

SELECT * FROM CART;

update cart set result='n' where no=3;

SELECT MAX(NO) FROM ORDERS;

SELECT LAST_NUMBER FROM USER_SEQUENCES WHERE SEQUENCE_NAME='ORDER_NO_SEQ';

select distinct ono from order_view  where mid='test' and result='0' order by ono DESC


SELECT * FROM ORDERs;

SELECT * FROM CART c ;

update cart set RESULT_USEYN=2 where no=57;

SELECT NO,SUBJECT,CONTENT,REPLY,ID,REPLY_USEYN,WRITE_DATE FROM QNA WHERE id ='test' ORDER BY NO DESC;

SELECT * FROM QNA WHERE NO = 1;

insert into qna (SUBJECT,CONTENT,ID)values('테스트2', '질문내용2', 'test');

SELECT * FROM WORKER;

INSERT INTO WORKER VALUES ('test','123','testname','010-1111-1111');
INSERT INTO WORKER VALUES ('admin','1234','yesman','010-1111-1111');

SELECT NO,REG_DATE,NAME,PRICE,SALEPRICE,DEL_USEYN,BEST_USEYN FROM PRODUCT WHERE NAME LIKE ? ORDER BY NO DESC;

SELECT NO,REG_DATE,NAME,PRICE,SALEPRICE,DEL_USEYN,BEST_USEYN FROM PRODUCT;