SELECT * FROM new_pro_view ;

SELECT * FROM MEMBER;

SELECT NO,NAME,KIND,PRICE,SALEPRICE,MARGIN,CONTENT,IMAGE,DEL_USEYN,BEST_USEYN,REG_DATE FROM PRODUCT;

SELECT ID,PWD,NAME,EMAIL,ZIP_NO,ADDRESS,PHONE,UNSIGN_USEYN,JOIN_DATE FROM MEMBER WHERE ID = 'one';

 INSERT INTO MEMBER(ID, PWD, NAME, ZIP_NO, ADDRESS, PHONE) VALUES (?, ?,?, ?, ?, ?);
 
SELECT ZIP_NO,SIDO,GUGUN,DONG,ZIP_CODE,BUNJI FROM ADDRESS WHERE DONG LIKE '%'||'진달'||'%';

SELECT * FROM  CART;

SELECT NO,MEMBERID,PNO,QUANTITY,RESULT_USEYN,REG_DATE FROM CART WHERE memberid = 'test' ORDER BY NO ASC;

insert into cart(MEMBERID, NO , quantity) values('one', 2, 1);
insert into cart(MEMBERID,PNO,QUANTITY,REG_DATE) values('test', 21, 3, sysdate);

DELETE FROM CART WHERE NO = 2;;

SELECT * FROM CART LEFT JOIN ;

select od.NO,ONO,PNO,QUANTITY,RESULT_USEYN,ID,ORDER_DATE from ORDER_DETAIL od LEFT JOIN ORDERS o ON(o.NO = od.ONO ) where id='test' and result_useyn like '%'||'y'||'%' and o.NO=5;

select od.NO,ONO,PNO,QUANTITY,RESULT_USEYN,ID,ORDER_DATE from ORDER_DETAIL od LEFT JOIN ORDERS o ON(o.NO = od.ONO ) where id='test' and result_useyn='y' order by o.no DESC;

SELECT MAX(no) FROM ORDERS;

SELECT * FROM ORDERS;

select od.NO,ONO,PNO,QUANTITY,RESULT_USEYN,ID,ORDER_DATE from ORDER_DETAIL od LEFT JOIN ORDERS o ON(o.NO = od.ONO );

SELECT * FROM CART;

update cart set result='n' where no=3;