SELECT * FROM new_pro_view ;

SELECT NO,NAME,KIND,PRICE,SALEPRICE,MARGIN,CONTENT,IMAGE,DEL_USEYN,BEST_USEYN,REG_DATE FROM PRODUCT;

SELECT ID,PWD,NAME,EMAIL,ZIP_NO,ADDRESS,PHONE,UNSIGN_USEYN,JOIN_DATE FROM MEMBER WHERE ID = 'one';

 INSERT INTO MEMBER(ID, PWD, NAME, ZIP_NO, ADDRESS, PHONE) VALUES (?, ?,?, ?, ?, ?);
 
SELECT ZIP_NO,SIDO,GUGUN,DONG,ZIP_CODE,BUNJI FROM ADDRESS WHERE DONG LIKE '%'||'진달'||'%';

